version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80" # 80 is the port nginx listening on
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build: . # build our own custom image
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chenlee
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis

volumes:
  mongo-db: